### ISSUE TITLE
Eliminate the dependence on Rakudobrew

### ISSUE THREAD

**Issue by JJ** [JJ/alpine-perl6#13]
The main problem is that due to its new configuration it's making all builds with the old Dockerfile fail. This is probably not important, anyway, since the old builds are still available

```
Cloning into '/root/.rakudobrew'...
The shell hook required to use rakudobrew in 'env' mode and use the 'shell' command seems not to be installed.
Run 'rakudobrew init' for installation instructions.
```

But the main problem is that it introduces a dependency for perl which is probably not needed. We are not going to use rakudobrew per se, to manage versions, so we might explore the possibility of deleting it after using it.

**Comment by Scimon** [comment]
I made a Docker image using the packages by @nxadm this is a stripped down version I think will work : 

```
FROM alpine:latest

ENTRYPOINT perl6 

ENV PATH "/opt/rakudo-pkg/bin/:${PATH}"

RUN apk update && apk upgrade \
        && apk add --no-cache curl git \
        && curl -L https://github.com/nxadm/rakudo-pkg/releases/download/v2019.11/rakudo-pkg-Alpine3.10_2019.11-01_x86_64.apk > rakudo-pkg-Alpine3.10_2019.11-01_x86_64.apk \
        && apk add --no-cache --allow-untrusted rakudo-pkg-Alpine3.10_2019.11-01_x86_64.apk \
```

This gives you `raku` and `zef` as root. Worth a look?

**Comment by JJ** [comment]
Most probably. Thanks!

**Comment by JJ** [comment]
Will also eliminate the perl dependence we have with rakudobrew...

**Comment by Scimon** [comment]
Another thought is have : 
```
&& curl -L https://github.com/nxadm/rakudo-pkg/releases/download/v2019.11/rakudo-pkg-Alpine3.10_2019.11-01_x86_64.apk > rakudo-pkg.apk \
        && apk add --no-cache --allow-untrusted rakudo-pkg.apk
```
Which then allows for easy templating. The Docker image can be updated when the new packages are built :smile_cat:

**Comment by nxadm** [comment]
Hi @Scimon,

I would use ARG so you don't have to change the Dockerfile with each release (and moved the ENTRYPOINT to the exec form instead of the shell form):

```docker
FROM alpine:latest
ARG pkgurl
ENV PATH "/opt/rakudo-pkg/bin/:${PATH}"

RUN apk update && apk upgrade \
        && apk add --no-cache curl git \
        && curl -sSLO $pkgurl \
        && apk add --no-cache --allow-untrusted *.apk

ENTRYPOINT [ "raku" ] 
```

**Comment by JJ** [comment]
As a matter of fact, I started to use ARG experimentally in the older
versions. Check out 2018.11, for instance.

I will try also and avoid having so many Dockerfiles around. Apparently,
you can override the pre-build step and call build with different arguments.

Also, use a GitHub action to upload them to the GitHub registry... All
that, probably, after the Advent Calendar at the earliest.

**Comment by Scimon** [comment]
Awesome! :+1:
