### ISSUE TITLE
Push to Docker hub the latest version both with a 'latest' tag  and a 'version' tag

### ISSUE THREAD

**Issue by stoned** [JJ/alpine-perl6#21]
It would be IMHO useful to have the latest version of this container image available on the Docker hub both with the 'latest' tag and with a 'version' tag. As an example, this would permit, as of today, to pull the image with Rakudo version 2020.12  both with the 'latest' tag and with the tag '2020.12'.

**Comment by JJ** [comment]
Will do. Thanks for the report.
