### ISSUE TITLE
curl: (48) An unknown option was passed in to libcurl

### ISSUE THREAD

**Issue by melezhik** [JJ/alpine-perl6#3]
This is what I get when try to invoke curl from the latest image. 
According to this - https://stackoverflow.com/a/41651363/5147708 the issue is fixed by installing curl-dev package and this is true, at least work for me.

So the patch might be:

```
RUN apk add curl-dev
```

**Comment by JJ** [comment]
Thanks! Will patch and reissue.

**Comment by JJ** [comment]
I have been trying to generate a new version, but now rakudobrew fails, both locally and in the container. I have issued a bug report https://github.com/tadzik/rakudobrew/issues/119

**Comment by melezhik** [comment]
👍
